---
title: "Getting Started with the AzureML Package"
date: "`r Sys.Date()`"
output:
  html_document
vignette: >
  %\VignetteIndexEntry{Getting Started with the AzureML package}
  %\VignetteEngine{knitr::rmarkdown}
---

# Getting Started with AzureML

Use this package to upload and download datasets to and from AzureML,
to interrogate experiments, to publish new R-based web services, and
to run R data through existing web services and retrieve the output.

# Installation instructions

Install the development version of the package directly from GitHub
with:
```r
# Install devtools
if(!require("devtools")) install.packages("devtools")
devtools::install_github("RevolutionAnalytics/azureml")
```
The package requires the `jsonlite, curl, miniCRAN, base64enc` and `uuid` packages.

# Overview

AzureML provides an interface to publish web services on Microsoft Azure
Machine Learning (Azure ML) from your local R environment. The main
functions in the package cover:

- Workspace: connect to and manage AzureML workspaces
- Datasets: upload and download datasets to and from AzureML workspaces
- Publish: define a custom function or train a model and publish it as an Azure Web Service
- Consume: use available web services from R in a variety of convenient formats

This is a technology preview. The APIs used by the package are still subject to
change. Please send any bugs or comments you have to the maintainers listed.

## Getting Started

To get started, please go [here](https://studio.azureml.net) and create a free
account (not guest) or use your existing Azure ML account.  After logging in,
under the "Settings" tab, copy and paste your Workspace ID from the "Name"
sub-tab into your R console. From the "Authorization Tokens" sub-tab, copy your
Primary Authorization Token into your R console. You will need this information
to access all package functionality.

The package defines a `Workspace` class that represents an AzureML work space.
Most of the functions in the package refer to a Workspace object directly or
indirectly. Use the `workspace` function to create Workspace objects, either
by explicitly specifying an AzureML workspace ID and authorization token:

```r
library(AzureML)
ws <- workspace(id="your workspace ID", auth="your authorization token")
```
or alternatively create a file in `~/.azureml/settings.json` with the
JSON structure (`api_endpoint` and `management_endpoint` are optional):
```
{"workspace": {
   "id":"test_id",
   "authorization_token": "test_token",
   "api_endpoint": "api_endpoint",
   "management_endpoint": "management_endpoint"
}}
```
See `?worspace` for more details.

## Examining workspace datasets, experiments and services

The `datasets`, `experiments`, and `services` function return data frames that
contain information about those objects available in the workspace. The package
caches the objects in the workspace environment, and that cache can be
refreshed at any time with the `refresh` function. Dataframes make it
relatively easy to sort and filter the datasets, experiments, and servies in
arbitrary ways.  The functions also include filtering options for specific and
common filters, like looking up something by name.

Use the `download.datasets` and `upload.dataset` to download or upload data
between R and your Azure workspace. The `download.intermediate.dataset`
function can download ephemeral data from a port in an experiment that is not
explicitly stored in your Azure workspace. Use `delete.datasets` to remove
and delete datasets from the workspace.

The `endpoints` function describes Azure web service endpoints, and works
with supporting help functions like `discoverSchema` and `endpointHelp`.

The `publishWebService` function publishes a custom R function as an AzureML
web service, available for use by any client.

Use the `comsume` function to evaluate an Azure ML web service with uploaded
R data.



## Detailed Example


WRITE ME
